config/routes.rb
Rails.application.routes.draw do
  post 'transaction' => "checkout#create", as: :proceed_checkout
  get 'checkout/new/:plan_name' => "checkout#new", as: :new_checkout

  post "/checkout/:id" => "checkout#show", as: :checkout
  post "/hook" => "home#hook"

  get 'home/index'

  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkout.rb
class Checkout < ApplicationRecord
  validates_presence_of :full_name, :email, :plan_name, :plan_price

  def paypal_url(business_email, return_path)
    values = {
            business: business_email,
            cmd: "_xclick",
            upload: 1,
            return: "#{Rails.application.secrets.app_host}#{return_path}",
            invoice: id,
            amount: 4000,
            item_name: self.plan_name.humanize,
            item_number: rand(50),
            quantity: '1',
            notify_url: "#{Rails.application.secrets.app_host}/hook"
        }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  protect_from_forgery

  def new
    @plan = params[:plan].merge!(plan_name: params[:plan_name])
    @checkout = Checkout.new(@plan)
  end

  def create
    @checkout = Checkout.new(checkout_params)
    if @checkout.save
      flash[:notice] = "Thank you for purchasing item."
      redirect_to @checkout.paypal_url(params[:checkout][:business_email], checkout_path(@checkout.id))
    else
      render :new
    end
  end

  def show
    redirect_to root_path
  end

  def checkout_params
    params.require(:checkout).permit(:full_name, :address, :email, :plan_name, :plan_price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery except: [:hook]
  
  def index
  end

  def hook
    params.permit! # Permit all Paypal input params
    status = params[:payment_status]
    if status == "Completed"
      @checkout = Checkout.find params[:invoice]
      @checkout.update_attributes notification_params: params, status: status, transaction_id: params[:txn_id], purchased_at: Time.now
    end
    render nothing: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def plan_name_class(plan_name)
    case plan_name
    when "gold"
      "warning"
    when "brownz"
      "dull"
    else
      "success"
    end
  end

  def validation_errors_notifications(object)
    return '' if object.errors.empty?

    messages = object.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-danger alert-block"> <button type="button"
      class="close" data-dismiss="alert">x</button>
      #{messages}
      </div>
    HTML

    html.html_safe
  end

  def alert_class_for flash_type
    case flash_type.to_sym
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
    end
  end

  def icon_class_for flash_type
    case flash_type.to_sym
      when :success
        "glyphicon-ok"
      when :error
        "glyphicon-remove"
      when :alert
        "glyphicon-remove"
      when :notice
        "glyphicon-ok"
    end
  end
end

app/views/checkout/new.html.erb
<div class="checkout">
  <div class="plan_heading">
    <span class="name text-<%= plan_name_class(@checkout.plan_name) %>"><%= @checkout.plan_name.capitalize %></span>
    <span class="price"><%= number_to_currency(@checkout.plan_price) %></span>
    <small>/ Monthly Plan</small>
  </div>
  <hr>

  <div class="form-container">
    <%= validation_errors_notifications(@checkout) %>
    <%= form_for @checkout, url: proceed_checkout_path, method: :post do |f| %>
    <%= f.hidden_field :plan_name, value: @checkout.plan_name %>
    <%= f.hidden_field :plan_price, value: @checkout.plan_price %>
    <%= f.hidden_field :business_email, value: "ali.ahmed.cs2016-facilitator-1@gmail.com" %>
      <div class="form-group <%= @checkout.errors.details[:full_name].present? ? 'has-error' : '' %>">
        <%=  %>
        <%= f.text_field :full_name, class: "form-control", placeholder: "Enter Fullname" %>
      </div>
      <div class="form-group">
        <%= f.text_field :address, class: "form-control", placeholder: "Enter Address" %>
      </div>
      <div class="form-group <%= @checkout.errors.details[:email].present? ? 'has-error' : '' %>">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter Email" %>
      </div>

      <div class="form-group form-actions">
        <%= f.submit "Pay (#{number_to_currency(@checkout.plan_price)})", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/checkout/show.html.erb
Hello

app/views/home/index.html.erb
<div class="fruitland">
  <div class="row">
    <div class="col-md-4">

      <div class="panel panel-primary" data-redirect="<%= new_checkout_path(:brownz, :plan => { plan_price: 100 }) %>">
        <div class="panel-heading">
          <div class="panel-title">
            <strong>Brownz Offer</strong>
          </div>
        </div>
        <div class="panel-body">
          <div class="plans">
            <strong><%= number_to_currency(100) %></strong><small>/ Monthly Plan</small>
          </div>
          <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, </li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
          </ul>
        </div>
      </div>

    </div>
    <div class="col-md-4">

      <div class="panel panel-warning" data-redirect="<%= new_checkout_path(:gold, :plan => { plan_price: 500 }) %>">
        <div class="panel-heading">
          <div class="panel-title">
            <strong>Gold Offer</strong>
          </div>
        </div>
        <div class="panel-body">
          <div class="plans gold">
            <strong><%= number_to_currency(500) %></strong><small>/ Monthly Plan</small>
          </div>
          <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, </li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
          </ul>
        </div>
      </div>

    </div>
    <div class="col-md-4">

      <div class="panel panel-success" data-redirect="<%= new_checkout_path(:silver, :plan => { plan_price: 200 }) %>">
        <div class="panel-heading">
          <div class="panel-title">
            <strong>Silver Offer</strong>
          </div>
        </div>
        <div class="panel-body">
          <div class="plans">
            <strong><%= number_to_currency(200) %></strong><small>/ Monthly Plan</small>
          </div>
          <ul>
            <li>Lorem ipsum dolor sit amet, consectetur adipisicing elit, </li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
            <li>sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
          </ul>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fruitland</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <h1 class="text-center page-header">
        <a href="<%= root_path %>">Fruitland</a>
      </h1>
      <% flash.each do |type, message| %>
        <div class="alert <%= alert_class_for(type) %> fade in">
          <strong><span class="glyphicon <%= icon_class_for(type) %>"></span>
            <button class="close" data-dismiss="alert">×</button>
            <%= message.html_safe %>
          </strong>
        </div>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>